package com.rifeng.p2p.db.greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.rifeng.p2p.entity.PipeCodeModel;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PIPE_CODE_MODEL".
*/
public class PipeCodeModelDao extends AbstractDao<PipeCodeModel, Long> {

    public static final String TABLENAME = "PIPE_CODE_MODEL";

    /**
     * Properties of entity PipeCodeModel.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property PipeCode = new Property(1, String.class, "pipeCode", false, "PIPE_CODE");
        public final static Property TempTestId = new Property(2, String.class, "tempTestId", false, "TEMP_TEST_ID");
    }


    public PipeCodeModelDao(DaoConfig config) {
        super(config);
    }
    
    public PipeCodeModelDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PIPE_CODE_MODEL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"PIPE_CODE\" TEXT," + // 1: pipeCode
                "\"TEMP_TEST_ID\" TEXT);"); // 2: tempTestId
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_PIPE_CODE_MODEL_PIPE_CODE_DESC_TEMP_TEST_ID_DESC ON \"PIPE_CODE_MODEL\"" +
                " (\"PIPE_CODE\" DESC,\"TEMP_TEST_ID\" DESC);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PIPE_CODE_MODEL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, PipeCodeModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pipeCode = entity.getPipeCode();
        if (pipeCode != null) {
            stmt.bindString(2, pipeCode);
        }
 
        String tempTestId = entity.getTempTestId();
        if (tempTestId != null) {
            stmt.bindString(3, tempTestId);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, PipeCodeModel entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String pipeCode = entity.getPipeCode();
        if (pipeCode != null) {
            stmt.bindString(2, pipeCode);
        }
 
        String tempTestId = entity.getTempTestId();
        if (tempTestId != null) {
            stmt.bindString(3, tempTestId);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public PipeCodeModel readEntity(Cursor cursor, int offset) {
        PipeCodeModel entity = new PipeCodeModel( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // pipeCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // tempTestId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, PipeCodeModel entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setPipeCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTempTestId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(PipeCodeModel entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(PipeCodeModel entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(PipeCodeModel entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
